### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by raghavbharadwaj** [SE7ENSKY/gitlab-webhook-youtrack#3]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with gitlab-webhook-youtrack. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable gitlab-webhook-youtrack on @Sourcegraph by going to https://sourcegraph.com/github.com/Se7enSky/gitlab-webhook-youtrack and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by ivankravchenko** [comment]
done
